Repository Intro-to-SE-lab-Spring-22/Group-6, pull requests merged in 2022-04, with the labels that each got.

#41 Agreen27/issue21
  source-code/css/style.css
  source-code/home.php
Labels: enhancement

#43 Create post functionality manually generates post ID instead of using…
  source-code/create_post.php
Labels: bug

#44 outline of basic ajax idea.
  source-code/home.php
Labels: enhancement

#45 fixing css layout
  source-code/css/style.css
Labels: bug

#46 Tankwhitman/issue21pt2
  source-code/css/style.css
  source-code/getpost.php
  source-code/home.php
Labels: enhancement

#49 32 user page styling
  source-code/css/style.css
  source-code/getpost.php
  source-code/home.php
  source-code/userpage.php
Labels: bug, enhancement

#48 Liking Posts Functionality
  source-code/css/style.css
  source-code/getpost.php
  source-code/home.php
  source-code/like_post.php
Labels: enhancement

#52 Post loading bug after pull request
  source-code/getpost.php
Labels: bug

#55 Add like post functionality to userpage/Post creation date improperly aligned
  source-code/getpost.php
  source-code/userpage.php
Labels: bug, enhancement

#56 Agreen27/issue36
  source-code/create_post.php
  source-code/css/style.css
  source-code/edit_post.php
  source-code/post.php
Labels: enhancement

#58 Update some UI links
  source-code/css/style.css
  source-code/getpost.php
  source-code/home.php
  source-code/post.php
  source-code/userpage.php
Labels: bug

#59 Commenting on Posts Functionality
  source-code/add_comment.php
  source-code/edit_comment.php
  source-code/post.php
Labels: enhancement

#65 General bug fixes
  source-code/getpost.php
Labels: bug

#68 More bug fixes
  source-code/post.php
  source-code/search.php
Labels: bug

#73 70 comment on code
  source-code/Controller/register.php
  source-code/add_comment.php
  source-code/create_post.php
  source-code/edit_comment.php
  source-code/edit_post.php
  source-code/friend_request.php
  source-code/getpost.php
  source-code/home.php
  source-code/index.php
  source-code/like_post.php
  source-code/login.php
  source-code/logout.php
  source-code/post.php
  source-code/search.php
  source-code/userpage.php
  source-code/verify_user.php
Labels: documentation

#78 Agreen27/issue77
  source-code/add_comment.php
  source-code/create_post.php
  source-code/edit_comment.php
  source-code/edit_post.php
  source-code/friend_request.php
  source-code/getpost.php
  source-code/index.php
  source-code/like_post.php
  source-code/login.php
  source-code/post.php
  source-code/search.php
  source-code/sql_queries.php
  source-code/userpage.php
Labels: refactoring

#79 update to front end html pages
  source-code/home.php
  source-code/navbar.php
  source-code/post.php
  source-code/search.php
  source-code/userpage.php
Labels: enhancement, refactoring

#81 Profile picture functionality
  images/profile/default.png
  source-code/Controller/register.php
  source-code/add_comment.php
  source-code/create_acct.php
  source-code/css/style.css
  source-code/edit_post.php
  source-code/index.php
  source-code/js/functions.js
  source-code/js/post_requests.js
  source-code/php/controller.php
  source-code/php/credentials.php
  source-code/php/functions.php
  source-code/php/sql_queries.php
  source-code/post.php
  source-code/search.php
  source-code/userpage.php
Labels: enhancement

#82 Refactoring home page
  source-code/getpost.php
  source-code/home.php
  source-code/js/functions.js
Labels: refactoring

#84 Auto refresh content on home page
  source-code/home.php
  source-code/js/functions.js
  source-code/js/post_requests.js
  source-code/php/functions.php
Labels: enhancement

#88 Image functionality
  source-code/create_post.php
  source-code/css/style.css
  source-code/getpost.php
  source-code/home.php
  source-code/js/functions.js
  source-code/js/post_requests.js
  source-code/php/controller.php
  source-code/php/functions.php
Labels: enhancement
